- name: SQL Create DB with Script
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    login_user: sa
    login_password: "{{ mssql_password }}"
    instance_name: "{{ ansible_host | default(ansible_ssh_host) | default(inventory_hostname) }}"
  roles:
    - sql-run-sql-script