---
nodes:
  - name: sql1
    role: sql
    app_name: mssql_demo
    vm_size: Standard_A1_v2
    os_type: Windows
#    image:
#      sku: Enterprise
#      publisher: MicrosoftSQLServer
#      version: latest
#      offer: SQL2014SP2-WS2012R2
    image:
      sku: 2019-Datacenter-Core-smalldisk
      publisher: MicrosoftWindowsServer
      version: latest
      offer: WindowsServer